package com.hackerai.rootspoofer;

import android.app.*;
import android.content.Intent;
import android.os.*;
import com.hackerai.rootspoofer.utils.ApkPatcher;
import java.io.File;

public class PatcherService extends Service {

    private static final int NOTIF_ID = 1337;
        private NotificationManager nm;

            @Override
                public void onCreate() {
                        super.onCreate();
                                nm = (NotificationManager) getSystemService(NOTIFICATION_SERVICE);
                                        
                                                NotificationChannel channel = new NotificationChannel(
                                                            "patcher", "APK Patcher", NotificationManager.IMPORTANCE_LOW);
                                                                    nm.createNotificationChannel(channel);
                                                                        }

                                                                            @Override
                                                                                public int onStartCommand(Intent intent, int flags, int startId) {
                                                                                        String apkPath = intent.getStringExtra("apk_path");
                                                                                                boolean injectFrida = intent.getBooleanExtra("inject_frida", true);
                                                                                                        boolean autoInstall = intent.getBooleanExtra("auto_install", true);

                                                                                                                Notification notification = new Notification.Builder(this, "patcher")
                                                                                                                            .setContentTitle("RootSpoofer")
                                                                                                                                        .setContentText("Patching APK...")
                                                                                                                                                    .setSmallIcon(android.R.drawable.ic_menu_edit)
                                                                                                                                                                .setOngoing(true)
                                                                                                                                                                            .build();
                                                                                                                                                                                    startForeground(NOTIF_ID, notification);

                                                                                                                                                                                            new Thread(() -> {
                                                                                                                                                                                                        ApkPatcher patcher = new ApkPatcher(this, new ApkPatcher.ProgressCallback() {
                                                                                                                                                                                                                        @Override
                                                                                                                                                                                                                                        public void onProgress(String message, int percent) {
                                                                                                                                                                                                                                                            updateNotification(message, percent);
                                                                                                                                                                                                                                                                                // Send broadcast to Activity for UI update
                                                                                                                                                                                                                                                                                                    Intent broadcast = new Intent("com.hackerai.rootspoofer.PROGRESS");
                                                                                                                                                                                                                                                                                                                        broadcast.putExtra("message", message);
                                                                                                                                                                                                                                                                                                                                            broadcast.putExtra("percent", percent);
                                                                                                                                                                                                                                                                                                                                                                sendBroadcast(broadcast);
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                @Override
                                                                                                                                                                                                                                                                                                                                                                                                                public void onError(String error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    updateNotification("Error: " + error, -1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Intent broadcast = new Intent("com.hackerai.rootspoofer.PROGRESS");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            broadcast.putExtra("error", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sendBroadcast(broadcast);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stopForeground(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stopSelf();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public void onComplete(String outputPath) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updateNotification("Complete: " + outputPath, 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Intent broadcast = new Intent("com.hackerai.rootspoofer.PROGRESS");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    broadcast.putExtra("complete", outputPath);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sendBroadcast(broadcast);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stopForeground(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                stopSelf();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        patcher.patch(apkPath, injectFrida, autoInstall);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (Exception e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    updateNotification("Fatal: " + e.getMessage(), -1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }).start();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return START_REDELIVER_INTENT;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        private void updateNotification(String text, int progress) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Notification.Builder builder = new Notification.Builder(this, "patcher")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setContentTitle("RootSpoofer")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setContentText(text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .setSmallIcon(android.R.drawable.ic_menu_edit)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .setOngoing(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (progress >= 0 && progress <= 100) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            builder.setProgress(100, progress, false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else if (progress < 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                builder.setProgress(0, 0, true); // indeterminate
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nm.notify(NOTIF_ID, builder.build());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public IBinder onBind(Intent intent) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }